module.exports = {
  anger: 'mad',
  contempt: 'bitch please',
  disgust: 'do not want',
  fear: 'scared',
  happiness: 'happy',
  neutral: 'chill',
  sadness: 'sad',
  surprise: 'surprised',
  'happiness neutral': 'ok',
  'disgust neutral': 'do not want',
  'neutral sadness': 'meh',
  'happiness sadness': 'idk',
  'happiness surprise': 'excited',
  'anger happiness': 'this is fine',
  'contempt happiness': 'unimpressed',
  'disgust happiness': 'unimpressed',
  'neutral surprise': 'what',
  'anger neutral': 'annoyed',
  'contempt neutral': 'meh'
};
